import { Vuepress } from '@vuepress/client'

const routeItems = [
  ["v-147825fb","/docs/",{"title":"主页"},["/docs/index.html","/docs/README.md"]],
  ["v-47ba7ca0","/docs/dotnet/",{"title":".NET"},["/docs/dotnet/index.html","/docs/dotnet/README.md"]],
  ["v-09cd5ccb","/docs/en/",{"title":"Home"},["/docs/en/index.html","/docs/en/README.md"]],
  ["v-95acbb24","/docs/guide/",{"title":"方向"},["/docs/guide/index.html","/docs/guide/README.md"]],
  ["v-5324d60e","/docs/database/sqlserver/advance.html",{"title":"高级语法"},["/docs/database/sqlserver/advance","/docs/database/sqlserver/advance.md"]],
  ["v-3bc4732c","/docs/database/sqlserver/function.html",{"title":"函数"},["/docs/database/sqlserver/function","/docs/database/sqlserver/function.md"]],
  ["v-36aff6f7","/docs/database/sqlserver/",{"title":"基本语法"},["/docs/database/sqlserver/index.html","/docs/database/sqlserver/README.md"]],
  ["v-6f45d325","/docs/database/sqlserver/reference.html",{"title":"参考"},["/docs/database/sqlserver/reference","/docs/database/sqlserver/reference.md"]],
  ["v-b01210ec","/docs/database/sqlserver/sqlserver-sync-to-mysql.html",{"title":"SQL Server 同步 MySql"},["/docs/database/sqlserver/sqlserver-sync-to-mysql","/docs/database/sqlserver/sqlserver-sync-to-mysql.md"]],
  ["v-1232e268","/docs/database/sqlserver/sqlserver-sync-to-oracle.html",{"title":"SQL Server 同步 Oracle"},["/docs/database/sqlserver/sqlserver-sync-to-oracle","/docs/database/sqlserver/sqlserver-sync-to-oracle.md"]],
  ["v-4c61c0ec","/docs/database/sqlserver/tips.html",{"title":"小技巧"},["/docs/database/sqlserver/tips","/docs/database/sqlserver/tips.md"]],
  ["v-6bee8d76","/docs/dotnet/abp.vnext/data-dictionary.html",{"title":"数据字典"},["/docs/dotnet/abp.vnext/data-dictionary","/docs/dotnet/abp.vnext/data-dictionary.md"]],
  ["v-524183e5","/docs/dotnet/abp.vnext/",{"title":"官方"},["/docs/dotnet/abp.vnext/index.html","/docs/dotnet/abp.vnext/README.md"]],
  ["v-7678a3a8","/docs/dotnet/abp.zero/",{"title":"ABP.Zero"},["/docs/dotnet/abp.zero/index.html","/docs/dotnet/abp.zero/README.md"]],
  ["v-244c8528","/docs/dotnet/design-pattern/abstract-factory.html",{"title":"抽象工厂(Abstract Factory)"},["/docs/dotnet/design-pattern/abstract-factory","/docs/dotnet/design-pattern/abstract-factory.md"]],
  ["v-ca675996","/docs/dotnet/design-pattern/adapter-pattern.html",{"title":"适配器模式(Adapter Pattern)"},["/docs/dotnet/design-pattern/adapter-pattern","/docs/dotnet/design-pattern/adapter-pattern.md"]],
  ["v-53ddaf1f","/docs/dotnet/design-pattern/bridge-pattern.html",{"title":"桥接模式(Bridge Pattern)"},["/docs/dotnet/design-pattern/bridge-pattern","/docs/dotnet/design-pattern/bridge-pattern.md"]],
  ["v-3830db68","/docs/dotnet/design-pattern/builder.html",{"title":"建造者模式(Builder)"},["/docs/dotnet/design-pattern/builder","/docs/dotnet/design-pattern/builder.md"]],
  ["v-f1e87f28","/docs/dotnet/design-pattern/chain-of-responsibility-pattern.html",{"title":"职责链模式(Chain of Responsibility Pattern)"},["/docs/dotnet/design-pattern/chain-of-responsibility-pattern","/docs/dotnet/design-pattern/chain-of-responsibility-pattern.md"]],
  ["v-d4051e8e","/docs/dotnet/design-pattern/command-pattern.html",{"title":"命令模式(Command Pattern)"},["/docs/dotnet/design-pattern/command-pattern","/docs/dotnet/design-pattern/command-pattern.md"]],
  ["v-a21ba906","/docs/dotnet/design-pattern/composite-pattern.html",{"title":"组合模式（Composite Pattern）"},["/docs/dotnet/design-pattern/composite-pattern","/docs/dotnet/design-pattern/composite-pattern.md"]],
  ["v-30f76b6e","/docs/dotnet/design-pattern/decorator-pattern.html",{"title":"装饰模式(Decorator Pattern)"},["/docs/dotnet/design-pattern/decorator-pattern","/docs/dotnet/design-pattern/decorator-pattern.md"]],
  ["v-32d7b4a4","/docs/dotnet/design-pattern/facade-pattern.html",{"title":"外观模式(Facade Pattern)"},["/docs/dotnet/design-pattern/facade-pattern","/docs/dotnet/design-pattern/facade-pattern.md"]],
  ["v-12699f32","/docs/dotnet/design-pattern/factory-method.html",{"title":"工厂方法模式(Factory Method)"},["/docs/dotnet/design-pattern/factory-method","/docs/dotnet/design-pattern/factory-method.md"]],
  ["v-0633cbd9","/docs/dotnet/design-pattern/flyweight-pattern.html",{"title":"享元模式(Flyweight Pattern)"},["/docs/dotnet/design-pattern/flyweight-pattern","/docs/dotnet/design-pattern/flyweight-pattern.md"]],
  ["v-3918922c","/docs/dotnet/design-pattern/interpreter-pattern.html",{"title":"解释器模式(Interpreter Pattern)"},["/docs/dotnet/design-pattern/interpreter-pattern","/docs/dotnet/design-pattern/interpreter-pattern.md"]],
  ["v-0ce669da","/docs/dotnet/design-pattern/iterator-pattern.html",{"title":"迭代器模式(Iterator Pattern)"},["/docs/dotnet/design-pattern/iterator-pattern","/docs/dotnet/design-pattern/iterator-pattern.md"]],
  ["v-13f94916","/docs/dotnet/design-pattern/mediator-pattern.html",{"title":"中介者模式(Mediator Pattern)"},["/docs/dotnet/design-pattern/mediator-pattern","/docs/dotnet/design-pattern/mediator-pattern.md"]],
  ["v-586d7a8b","/docs/dotnet/design-pattern/memento-pattern.html",{"title":"备忘录模式(Memento Pattern)"},["/docs/dotnet/design-pattern/memento-pattern","/docs/dotnet/design-pattern/memento-pattern.md"]],
  ["v-22456f1c","/docs/dotnet/design-pattern/observer-pattern.html",{"title":"观察者模式(Observer Pattern)"},["/docs/dotnet/design-pattern/observer-pattern","/docs/dotnet/design-pattern/observer-pattern.md"]],
  ["v-e63334b6","/docs/dotnet/design-pattern/prototype.html",{"title":"原型模式(Prototype)"},["/docs/dotnet/design-pattern/prototype","/docs/dotnet/design-pattern/prototype.md"]],
  ["v-e126ac14","/docs/dotnet/design-pattern/proxy-pattern.html",{"title":"代理模式(Proxy Pattern)"},["/docs/dotnet/design-pattern/proxy-pattern","/docs/dotnet/design-pattern/proxy-pattern.md"]],
  ["v-bbb7870e","/docs/dotnet/design-pattern/singleton-pattern.html",{"title":"单件模式(Singleton Pattern)"},["/docs/dotnet/design-pattern/singleton-pattern","/docs/dotnet/design-pattern/singleton-pattern.md"]],
  ["v-1bba80b3","/docs/dotnet/design-pattern/state-pattern.html",{"title":"状态模式(State Pattern)"},["/docs/dotnet/design-pattern/state-pattern","/docs/dotnet/design-pattern/state-pattern.md"]],
  ["v-121b9ef5","/docs/dotnet/design-pattern/strategy-pattern.html",{"title":"策略模式(Strategy Pattern)"},["/docs/dotnet/design-pattern/strategy-pattern","/docs/dotnet/design-pattern/strategy-pattern.md"]],
  ["v-7b8575f3","/docs/dotnet/design-pattern/template-method.html",{"title":"模板方法(Template Method)"},["/docs/dotnet/design-pattern/template-method","/docs/dotnet/design-pattern/template-method.md"]],
  ["v-80d46714","/docs/dotnet/design-pattern/visitor-pattern.html",{"title":"访问者模式(Visitor Pattern)"},["/docs/dotnet/design-pattern/visitor-pattern","/docs/dotnet/design-pattern/visitor-pattern.md"]],
  ["v-4ce039e5","/docs/dotnet/wpf/course1.html",{"title":"XAML概览"},["/docs/dotnet/wpf/course1","/docs/dotnet/wpf/course1.md"]],
  ["v-4e951284","/docs/dotnet/wpf/course2.html",{"title":"从零起步认识XAML"},["/docs/dotnet/wpf/course2","/docs/dotnet/wpf/course2.md"]],
  ["v-5049eb23","/docs/dotnet/wpf/course3.html",{"title":"系统学习XAML语法"},["/docs/dotnet/wpf/course3","/docs/dotnet/wpf/course3.md"]],
  ["v-4956fa62","/docs/dotnet/wpf/download.html",{"title":"下载"},["/docs/dotnet/wpf/download","/docs/dotnet/wpf/download.md"]],
  ["v-91ba147c","/docs/dotnet/wpf/",{"title":"简介"},["/docs/dotnet/wpf/index.html","/docs/dotnet/wpf/README.md"]],
  ["v-ee10ddc2","/docs/life/books/must-read-books.html",{"title":"人生必读书籍"},["/docs/life/books/must-read-books","/docs/life/books/must-read-books.md"]],
  ["v-c3bc9f46","/docs/life/books/",{"title":"古训·增广贤文"},["/docs/life/books/index.html","/docs/life/books/README.md"]],
  ["v-9d85577c","/docs/life/music/",{"title":"车载音乐"},["/docs/life/music/index.html","/docs/life/music/README.md"]],
  ["v-0f6bdd54","/docs/varietystore/ladder/google-recaptcha.html",{"title":"谷歌验证码"},["/docs/varietystore/ladder/google-recaptcha","/docs/varietystore/ladder/google-recaptcha.md"]],
  ["v-252a175c","/docs/varietystore/ladder/",{"title":"梯子"},["/docs/varietystore/ladder/index.html","/docs/varietystore/ladder/README.md"]],
  ["v-3496da58","/docs/web/jquery/define-key-board.html",{"title":"自定义键盘"},["/docs/web/jquery/define-key-board","/docs/web/jquery/define-key-board.md"]],
  ["v-4336dcbb","/docs/web/jquery/",{"title":"JQuery"},["/docs/web/jquery/index.html","/docs/web/jquery/README.md"]],
  ["v-1295ac4c","/docs/web/vue3/",{"title":"Vue"},["/docs/web/vue3/index.html","/docs/web/vue3/README.md"]],
  ["v-5aaa8bd0","/docs/dotnet/wpf/controls/button.html",{"title":"按钮控件"},["/docs/dotnet/wpf/controls/button","/docs/dotnet/wpf/controls/button.md"]],
  ["v-ff081692","/docs/dotnet/wpf/controls/",{"title":"自定义的一套轻量级UI控件"},["/docs/dotnet/wpf/controls/index.html","/docs/dotnet/wpf/controls/README.md"]],
  ["v-963d9f1a","/docs/dotnet/wpf/prism/course1.html",{"title":"反射加载自定义DLL"},["/docs/dotnet/wpf/prism/course1","/docs/dotnet/wpf/prism/course1.md"]],
  ["v-ef325d60","/docs/dotnet/wpf/prism/",{"title":"简介"},["/docs/dotnet/wpf/prism/index.html","/docs/dotnet/wpf/prism/README.md"]],
  ["v-239a6d81","/docs/life/literature/latex/latex-course1.html",{"title":"矩阵使用参考"},["/docs/life/literature/latex/latex-course1","/docs/life/literature/latex/latex-course1.md"]],
  ["v-5995c1c3","/docs/life/literature/latex/",{"title":"公式使用参考"},["/docs/life/literature/latex/index.html","/docs/life/literature/latex/README.md"]],
  ["v-becfaf7c","/docs/varietystore/cli/github/",{"title":"说明"},["/docs/varietystore/cli/github/index.html","/docs/varietystore/cli/github/README.md"]],
  ["v-946735a0","/docs/varietystore/cli/github/reference.html",{"title":"参考"},["/docs/varietystore/cli/github/reference","/docs/varietystore/cli/github/reference.md"]],
  ["v-2de5a281","/docs/varietystore/cli/yarn/",{"title":"说明"},["/docs/varietystore/cli/yarn/index.html","/docs/varietystore/cli/yarn/README.md"]],
  ["v-25fb852f","/docs/varietystore/cli/yarn/reference.html",{"title":"参考"},["/docs/varietystore/cli/yarn/reference","/docs/varietystore/cli/yarn/reference.md"]],
  ["v-1b966d6a","/docs/varietystore/data-exchange-format/json/read-json.html",{"title":"读取"},["/docs/varietystore/data-exchange-format/json/read-json","/docs/varietystore/data-exchange-format/json/read-json.md"]],
  ["v-3e097d91","/docs/varietystore/data-exchange-format/json/",{"title":"JSON简介"},["/docs/varietystore/data-exchange-format/json/index.html","/docs/varietystore/data-exchange-format/json/README.md"]],
  ["v-0e7ac43f","/docs/varietystore/data-exchange-format/json/reference.html",{"title":"参考"},["/docs/varietystore/data-exchange-format/json/reference","/docs/varietystore/data-exchange-format/json/reference.md"]],
  ["v-3ca63a5c","/docs/varietystore/data-exchange-format/json/write-json.html",{"title":"写入"},["/docs/varietystore/data-exchange-format/json/write-json","/docs/varietystore/data-exchange-format/json/write-json.md"]],
  ["v-56fe07cb","/docs/varietystore/data-exchange-format/xml/read-xml.html",{"title":"读取"},["/docs/varietystore/data-exchange-format/xml/read-xml","/docs/varietystore/data-exchange-format/xml/read-xml.md"]],
  ["v-0206946e","/docs/varietystore/data-exchange-format/xml/",{"title":"XML简介"},["/docs/varietystore/data-exchange-format/xml/index.html","/docs/varietystore/data-exchange-format/xml/README.md"]],
  ["v-0144145c","/docs/varietystore/data-exchange-format/xml/reference.html",{"title":"参考"},["/docs/varietystore/data-exchange-format/xml/reference","/docs/varietystore/data-exchange-format/xml/reference.md"]],
  ["v-a6768d84","/docs/varietystore/data-exchange-format/xml/write-xml.html",{"title":"写入"},["/docs/varietystore/data-exchange-format/xml/write-xml","/docs/varietystore/data-exchange-format/xml/write-xml.md"]],
  ["v-541994e1","/docs/varietystore/erp/yonyou/",{"title":"说明"},["/docs/varietystore/erp/yonyou/index.html","/docs/varietystore/erp/yonyou/README.md"]],
  ["v-49e6657a","/docs/varietystore/ladder/encryption/",{"title":"加密"},["/docs/varietystore/ladder/encryption/index.html","/docs/varietystore/ladder/encryption/README.md"]],
  ["v-57452d66","/docs/varietystore/ladder/machinecode/",{"title":"机器码"},["/docs/varietystore/ladder/machinecode/index.html","/docs/varietystore/ladder/machinecode/README.md"]],
  ["v-73b5bad9","/docs/varietystore/ladder/sounds/",{"title":"播放声音"},["/docs/varietystore/ladder/sounds/index.html","/docs/varietystore/ladder/sounds/README.md"]],
  ["v-14cb8fd6","/docs/varietystore/ladder/transform/",{"title":"转换"},["/docs/varietystore/ladder/transform/index.html","/docs/varietystore/ladder/transform/README.md"]],
  ["v-7cf145ba","/docs/varietystore/office/excel/macro-sample1.html",{"title":"考勤时间间隔统计"},["/docs/varietystore/office/excel/macro-sample1","/docs/varietystore/office/excel/macro-sample1.md"]],
  ["v-7987947c","/docs/varietystore/office/excel/macro-sample2.html",{"title":"中位数统计"},["/docs/varietystore/office/excel/macro-sample2","/docs/varietystore/office/excel/macro-sample2.md"]],
  ["v-761de33e","/docs/varietystore/office/excel/macro-sample3.html",{"title":"考勤迟到早退统计"},["/docs/varietystore/office/excel/macro-sample3","/docs/varietystore/office/excel/macro-sample3.md"]],
  ["v-50b52b9e","/docs/varietystore/office/excel/read-from-excel.html",{"title":"读取Excel"},["/docs/varietystore/office/excel/read-from-excel","/docs/varietystore/office/excel/read-from-excel.md"]],
  ["v-3d87b750","/docs/varietystore/office/excel/",{"title":"Excel简介"},["/docs/varietystore/office/excel/index.html","/docs/varietystore/office/excel/README.md"]],
  ["v-0254f884","/docs/varietystore/office/excel/reference.html",{"title":"参考"},["/docs/varietystore/office/excel/reference","/docs/varietystore/office/excel/reference.md"]],
  ["v-d609cf54","/docs/varietystore/office/excel/write-to-excel.html",{"title":"写入Excel"},["/docs/varietystore/office/excel/write-to-excel","/docs/varietystore/office/excel/write-to-excel.md"]],
  ["v-0a9fbd34","/docs/life/books/self-study/probability-and-statistics/basic-formula.html",{"title":"基本公式"},["/docs/life/books/self-study/probability-and-statistics/basic-formula","/docs/life/books/self-study/probability-and-statistics/basic-formula.md"]],
  ["v-131f55d2","/docs/life/books/self-study/probability-and-statistics/course1.html",{"title":"盛炎平-课程导学(一)"},["/docs/life/books/self-study/probability-and-statistics/course1","/docs/life/books/self-study/probability-and-statistics/course1.md"]],
  ["v-0fb5a494","/docs/life/books/self-study/probability-and-statistics/course2.html",{"title":"盛炎平-课程导学(二)"},["/docs/life/books/self-study/probability-and-statistics/course2","/docs/life/books/self-study/probability-and-statistics/course2.md"]],
  ["v-0c4bf356","/docs/life/books/self-study/probability-and-statistics/course3.html",{"title":"盛炎平-第一章 随机事件与概率(1)"},["/docs/life/books/self-study/probability-and-statistics/course3","/docs/life/books/self-study/probability-and-statistics/course3.md"]],
  ["v-08e24218","/docs/life/books/self-study/probability-and-statistics/course4.html",{"title":"盛炎平-第一章 随机事件与概率(2)"},["/docs/life/books/self-study/probability-and-statistics/course4","/docs/life/books/self-study/probability-and-statistics/course4.md"]],
  ["v-057890da","/docs/life/books/self-study/probability-and-statistics/course5.html",{"title":"盛炎平-第一章 随机事件与概率(3)"},["/docs/life/books/self-study/probability-and-statistics/course5","/docs/life/books/self-study/probability-and-statistics/course5.md"]],
  ["v-020edf9c","/docs/life/books/self-study/probability-and-statistics/course6.html",{"title":"盛炎平-第一章 随机事件与概率(4)"},["/docs/life/books/self-study/probability-and-statistics/course6","/docs/life/books/self-study/probability-and-statistics/course6.md"]],
  ["v-092ccbf4","/docs/life/books/self-study/probability-and-statistics/",{"title":"课程代号02197"},["/docs/life/books/self-study/probability-and-statistics/index.html","/docs/life/books/self-study/probability-and-statistics/README.md"]],
  ["v-9e547ec6","/docs/life/literature/markdown/extension/emoji.html",{"title":"Emoji表情"},["/docs/life/literature/markdown/extension/emoji","/docs/life/literature/markdown/extension/emoji.md"]],
  ["v-222e484c","/docs/life/literature/markdown/extension/others.html",{"title":"其他"},["/docs/life/literature/markdown/extension/others","/docs/life/literature/markdown/extension/others.md"]],
  ["v-2a77fa15","/docs/life/literature/markdown/extension/table.html",{"title":"表格"},["/docs/life/literature/markdown/extension/table","/docs/life/literature/markdown/extension/table.md"]],
  ["v-c92fa4bc","/docs/life/literature/markdown/extension/task-lists.html",{"title":"任务列表"},["/docs/life/literature/markdown/extension/task-lists","/docs/life/literature/markdown/extension/task-lists.md"]],
  ["v-a46d7386","/docs/life/literature/markdown/block%20elements/blockquotes.html",{"title":"块引用"},["/docs/life/literature/markdown/block elements/blockquotes.html","/docs/life/literature/markdown/block%20elements/blockquotes","/docs/life/literature/markdown/block elements/blockquotes.md","/docs/life/literature/markdown/block%20elements/blockquotes.md"]],
  ["v-2048a34a","/docs/life/literature/markdown/block%20elements/code-blocks.html",{"title":"代码块"},["/docs/life/literature/markdown/block elements/code-blocks.html","/docs/life/literature/markdown/block%20elements/code-blocks","/docs/life/literature/markdown/block elements/code-blocks.md","/docs/life/literature/markdown/block%20elements/code-blocks.md"]],
  ["v-f150478a","/docs/life/literature/markdown/block%20elements/headers.html",{"title":"标题"},["/docs/life/literature/markdown/block elements/headers.html","/docs/life/literature/markdown/block%20elements/headers","/docs/life/literature/markdown/block elements/headers.md","/docs/life/literature/markdown/block%20elements/headers.md"]],
  ["v-978c3d3a","/docs/life/literature/markdown/block%20elements/horizontal-rules.html",{"title":"水平线"},["/docs/life/literature/markdown/block elements/horizontal-rules.html","/docs/life/literature/markdown/block%20elements/horizontal-rules","/docs/life/literature/markdown/block elements/horizontal-rules.md","/docs/life/literature/markdown/block%20elements/horizontal-rules.md"]],
  ["v-68f678e8","/docs/life/literature/markdown/block%20elements/lists.html",{"title":"列表"},["/docs/life/literature/markdown/block elements/lists.html","/docs/life/literature/markdown/block%20elements/lists","/docs/life/literature/markdown/block elements/lists.md","/docs/life/literature/markdown/block%20elements/lists.md"]],
  ["v-4886a27c","/docs/life/literature/markdown/block%20elements/paragraphs-and-line-breaks.html",{"title":"段落和换行符"},["/docs/life/literature/markdown/block elements/paragraphs-and-line-breaks.html","/docs/life/literature/markdown/block%20elements/paragraphs-and-line-breaks","/docs/life/literature/markdown/block elements/paragraphs-and-line-breaks.md","/docs/life/literature/markdown/block%20elements/paragraphs-and-line-breaks.md"]],
  ["v-a4fd27c6","/docs/life/literature/markdown/miscellaneous/automatic-links.html",{"title":"自动连接"},["/docs/life/literature/markdown/miscellaneous/automatic-links","/docs/life/literature/markdown/miscellaneous/automatic-links.md"]],
  ["v-0bc75739","/docs/life/literature/markdown/miscellaneous/backslash-escapes.html",{"title":"反斜杠转义"},["/docs/life/literature/markdown/miscellaneous/backslash-escapes","/docs/life/literature/markdown/miscellaneous/backslash-escapes.md"]],
  ["v-d3683d74","/docs/life/literature/markdown/overview/automatic-escaping-for-special-characters.html",{"title":"特殊字符的自动转义"},["/docs/life/literature/markdown/overview/automatic-escaping-for-special-characters","/docs/life/literature/markdown/overview/automatic-escaping-for-special-characters.md"]],
  ["v-0d1d4914","/docs/life/literature/markdown/overview/inline-html.html",{"title":"内联HTML"},["/docs/life/literature/markdown/overview/inline-html","/docs/life/literature/markdown/overview/inline-html.md"]],
  ["v-d3bb7228","/docs/life/literature/markdown/overview/philosophy.html",{"title":"哲学"},["/docs/life/literature/markdown/overview/philosophy","/docs/life/literature/markdown/overview/philosophy.md"]],
  ["v-1a31b5da","/docs/life/literature/markdown/span%20elements/code.html",{"title":"代码"},["/docs/life/literature/markdown/span elements/code.html","/docs/life/literature/markdown/span%20elements/code","/docs/life/literature/markdown/span elements/code.md","/docs/life/literature/markdown/span%20elements/code.md"]],
  ["v-cf027938","/docs/life/literature/markdown/span%20elements/emphasis.html",{"title":"强调"},["/docs/life/literature/markdown/span elements/emphasis.html","/docs/life/literature/markdown/span%20elements/emphasis","/docs/life/literature/markdown/span elements/emphasis.md","/docs/life/literature/markdown/span%20elements/emphasis.md"]],
  ["v-2c5fecb0","/docs/life/literature/markdown/span%20elements/images.html",{"title":"图片"},["/docs/life/literature/markdown/span elements/images.html","/docs/life/literature/markdown/span%20elements/images","/docs/life/literature/markdown/span elements/images.md","/docs/life/literature/markdown/span%20elements/images.md"]],
  ["v-45b0b799","/docs/life/literature/markdown/span%20elements/links.html",{"title":"链接"},["/docs/life/literature/markdown/span elements/links.html","/docs/life/literature/markdown/span%20elements/links","/docs/life/literature/markdown/span elements/links.md","/docs/life/literature/markdown/span%20elements/links.md"]],
  ["v-5c96d7a8","/docs/varietystore/erp/yonyou/alarms/",{"title":"预警服务"},["/docs/varietystore/erp/yonyou/alarms/index.html","/docs/varietystore/erp/yonyou/alarms/README.md"]],
  ["v-d9758c4a","/docs/varietystore/erp/yonyou/archives/aa_bank.html",{"title":"银行档案"},["/docs/varietystore/erp/yonyou/archives/aa_bank","/docs/varietystore/erp/yonyou/archives/aa_bank.md"]],
  ["v-b627e994","/docs/varietystore/erp/yonyou/archives/assembly.html",{"title":"成套件"},["/docs/varietystore/erp/yonyou/archives/assembly","/docs/varietystore/erp/yonyou/archives/assembly.md"]],
  ["v-4f30e331","/docs/varietystore/erp/yonyou/archives/balance-type.html",{"title":"结算方式"},["/docs/varietystore/erp/yonyou/archives/balance-type","/docs/varietystore/erp/yonyou/archives/balance-type.md"]],
  ["v-80e10c80","/docs/varietystore/erp/yonyou/archives/bank-account.html",{"title":"银行对账单"},["/docs/varietystore/erp/yonyou/archives/bank-account","/docs/varietystore/erp/yonyou/archives/bank-account.md"]],
  ["v-3300c220","/docs/varietystore/erp/yonyou/archives/bank.html",{"title":"本单位开户银行"},["/docs/varietystore/erp/yonyou/archives/bank","/docs/varietystore/erp/yonyou/archives/bank.md"]],
  ["v-1a197514","/docs/varietystore/erp/yonyou/archives/batch-property.html",{"title":"批次档案"},["/docs/varietystore/erp/yonyou/archives/batch-property","/docs/varietystore/erp/yonyou/archives/batch-property.md"]],
  ["v-440c305f","/docs/varietystore/erp/yonyou/archives/capital-asset-types.html",{"title":"资产类别"},["/docs/varietystore/erp/yonyou/archives/capital-asset-types","/docs/varietystore/erp/yonyou/archives/capital-asset-types.md"]],
  ["v-8747ced8","/docs/varietystore/erp/yonyou/archives/capital-assets.html",{"title":"固定资产卡片"},["/docs/varietystore/erp/yonyou/archives/capital-assets","/docs/varietystore/erp/yonyou/archives/capital-assets.md"]],
  ["v-8aef6b40","/docs/varietystore/erp/yonyou/archives/code-balance.html",{"title":"期初余额"},["/docs/varietystore/erp/yonyou/archives/code-balance","/docs/varietystore/erp/yonyou/archives/code-balance.md"]],
  ["v-5a5a410f","/docs/varietystore/erp/yonyou/archives/code.html",{"title":"会计科目"},["/docs/varietystore/erp/yonyou/archives/code","/docs/varietystore/erp/yonyou/archives/code.md"]],
  ["v-7704082a","/docs/varietystore/erp/yonyou/archives/currency.html",{"title":"外币设置"},["/docs/varietystore/erp/yonyou/archives/currency","/docs/varietystore/erp/yonyou/archives/currency.md"]],
  ["v-8fd15c1a","/docs/varietystore/erp/yonyou/archives/customer-class.html",{"title":"客户分类"},["/docs/varietystore/erp/yonyou/archives/customer-class","/docs/varietystore/erp/yonyou/archives/customer-class.md"]],
  ["v-4095178f","/docs/varietystore/erp/yonyou/archives/customer-inventory.html",{"title":"客户存货对照表"},["/docs/varietystore/erp/yonyou/archives/customer-inventory","/docs/varietystore/erp/yonyou/archives/customer-inventory.md"]],
  ["v-7eacbdc0","/docs/varietystore/erp/yonyou/archives/customer-linker.html",{"title":"客户联系人"},["/docs/varietystore/erp/yonyou/archives/customer-linker","/docs/varietystore/erp/yonyou/archives/customer-linker.md"]],
  ["v-029b443e","/docs/varietystore/erp/yonyou/archives/customer.html",{"title":"客户档案"},["/docs/varietystore/erp/yonyou/archives/customer","/docs/varietystore/erp/yonyou/archives/customer.md"]],
  ["v-8c9b16ec","/docs/varietystore/erp/yonyou/archives/department.html",{"title":"部门档案"},["/docs/varietystore/erp/yonyou/archives/department","/docs/varietystore/erp/yonyou/archives/department.md"]],
  ["v-17732ad8","/docs/varietystore/erp/yonyou/archives/digest.html",{"title":"常用摘要"},["/docs/varietystore/erp/yonyou/archives/digest","/docs/varietystore/erp/yonyou/archives/digest.md"]],
  ["v-07637043","/docs/varietystore/erp/yonyou/archives/district-class.html",{"title":"地区分类"},["/docs/varietystore/erp/yonyou/archives/district-class","/docs/varietystore/erp/yonyou/archives/district-class.md"]],
  ["v-117adfb5","/docs/varietystore/erp/yonyou/archives/dsign.html",{"title":"凭证类别"},["/docs/varietystore/erp/yonyou/archives/dsign","/docs/varietystore/erp/yonyou/archives/dsign.md"]],
  ["v-3f36ca22","/docs/varietystore/erp/yonyou/archives/duty-level.html",{"title":"职务级别"},["/docs/varietystore/erp/yonyou/archives/duty-level","/docs/varietystore/erp/yonyou/archives/duty-level.md"]],
  ["v-4432f785","/docs/varietystore/erp/yonyou/archives/duty-type.html",{"title":"职务类别"},["/docs/varietystore/erp/yonyou/archives/duty-type","/docs/varietystore/erp/yonyou/archives/duty-type.md"]],
  ["v-632b4474","/docs/varietystore/erp/yonyou/archives/duty.html",{"title":"职务类别"},["/docs/varietystore/erp/yonyou/archives/duty","/docs/varietystore/erp/yonyou/archives/duty.md"]],
  ["v-50b42574","/docs/varietystore/erp/yonyou/archives/expense-item.html",{"title":"费用项目"},["/docs/varietystore/erp/yonyou/archives/expense-item","/docs/varietystore/erp/yonyou/archives/expense-item.md"]],
  ["v-5f6002fb","/docs/varietystore/erp/yonyou/archives/expitem-class.html",{"title":"费用项目分类"},["/docs/varietystore/erp/yonyou/archives/expitem-class","/docs/varietystore/erp/yonyou/archives/expitem-class.md"]],
  ["v-3f46dce2","/docs/varietystore/erp/yonyou/archives/inventory-class.html",{"title":"存货分类"},["/docs/varietystore/erp/yonyou/archives/inventory-class","/docs/varietystore/erp/yonyou/archives/inventory-class.md"]],
  ["v-2522e0ff","/docs/varietystore/erp/yonyou/archives/inventory-free.html",{"title":"存货自由项对照表"},["/docs/varietystore/erp/yonyou/archives/inventory-free","/docs/varietystore/erp/yonyou/archives/inventory-free.md"]],
  ["v-3f01b362","/docs/varietystore/erp/yonyou/archives/inventory-position.html",{"title":"存货货位对照表"},["/docs/varietystore/erp/yonyou/archives/inventory-position","/docs/varietystore/erp/yonyou/archives/inventory-position.md"]],
  ["v-193f68da","/docs/varietystore/erp/yonyou/archives/inventory.html",{"title":"存货档案"},["/docs/varietystore/erp/yonyou/archives/inventory","/docs/varietystore/erp/yonyou/archives/inventory.md"]],
  ["v-16baa85a","/docs/varietystore/erp/yonyou/archives/job-grade-set.html",{"title":"职等设置"},["/docs/varietystore/erp/yonyou/archives/job-grade-set","/docs/varietystore/erp/yonyou/archives/job-grade-set.md"]],
  ["v-abdbb75c","/docs/varietystore/erp/yonyou/archives/job-type.html",{"title":"职位序列"},["/docs/varietystore/erp/yonyou/archives/job-type","/docs/varietystore/erp/yonyou/archives/job-type.md"]],
  ["v-dca8b64e","/docs/varietystore/erp/yonyou/archives/job.html",{"title":"职位档案"},["/docs/varietystore/erp/yonyou/archives/job","/docs/varietystore/erp/yonyou/archives/job.md"]],
  ["v-f3dc1480","/docs/varietystore/erp/yonyou/archives/pay-condition.html",{"title":"付款条件"},["/docs/varietystore/erp/yonyou/archives/pay-condition","/docs/varietystore/erp/yonyou/archives/pay-condition.md"]],
  ["v-c15cfbf8","/docs/varietystore/erp/yonyou/archives/person-type.html",{"title":"人员类别"},["/docs/varietystore/erp/yonyou/archives/person-type","/docs/varietystore/erp/yonyou/archives/person-type.md"]],
  ["v-7070ffe7","/docs/varietystore/erp/yonyou/archives/person.html",{"title":"人员档案"},["/docs/varietystore/erp/yonyou/archives/person","/docs/varietystore/erp/yonyou/archives/person.md"]],
  ["v-7c257c5a","/docs/varietystore/erp/yonyou/archives/position.html",{"title":"货位档案"},["/docs/varietystore/erp/yonyou/archives/position","/docs/varietystore/erp/yonyou/archives/position.md"]],
  ["v-18911170","/docs/varietystore/erp/yonyou/archives/purchase-type.html",{"title":"采购类型"},["/docs/varietystore/erp/yonyou/archives/purchase-type","/docs/varietystore/erp/yonyou/archives/purchase-type.md"]],
  ["v-7ca1f350","/docs/varietystore/erp/yonyou/archives/reason.html",{"title":"原因码档案"},["/docs/varietystore/erp/yonyou/archives/reason","/docs/varietystore/erp/yonyou/archives/reason.md"]],
  ["v-b7333e3e","/docs/varietystore/erp/yonyou/archives/receive-send-type.html",{"title":"收发类别"},["/docs/varietystore/erp/yonyou/archives/receive-send-type","/docs/varietystore/erp/yonyou/archives/receive-send-type.md"]],
  ["v-766fb508","/docs/varietystore/erp/yonyou/archives/requirement-class.html",{"title":"需求分类"},["/docs/varietystore/erp/yonyou/archives/requirement-class","/docs/varietystore/erp/yonyou/archives/requirement-class.md"]],
  ["v-02ebb894","/docs/varietystore/erp/yonyou/archives/sale-type.html",{"title":"销售类型"},["/docs/varietystore/erp/yonyou/archives/sale-type","/docs/varietystore/erp/yonyou/archives/sale-type.md"]],
  ["v-536a6f54","/docs/varietystore/erp/yonyou/archives/shipping-choice.html",{"title":"发运方式"},["/docs/varietystore/erp/yonyou/archives/shipping-choice","/docs/varietystore/erp/yonyou/archives/shipping-choice.md"]],
  ["v-60163b78","/docs/varietystore/erp/yonyou/archives/unit-account.html",{"title":"交易单位账号"},["/docs/varietystore/erp/yonyou/archives/unit-account","/docs/varietystore/erp/yonyou/archives/unit-account.md"]],
  ["v-27272e0d","/docs/varietystore/erp/yonyou/archives/unit-class.html",{"title":"交易单位分类"},["/docs/varietystore/erp/yonyou/archives/unit-class","/docs/varietystore/erp/yonyou/archives/unit-class.md"]],
  ["v-5044b566","/docs/varietystore/erp/yonyou/archives/unit-doc.html",{"title":"交易单位档案"},["/docs/varietystore/erp/yonyou/archives/unit-doc","/docs/varietystore/erp/yonyou/archives/unit-doc.md"]],
  ["v-f6342534","/docs/varietystore/erp/yonyou/archives/unit-group.html",{"title":"计量单位组"},["/docs/varietystore/erp/yonyou/archives/unit-group","/docs/varietystore/erp/yonyou/archives/unit-group.md"]],
  ["v-fd3e8850","/docs/varietystore/erp/yonyou/archives/unit.html",{"title":"计量单位"},["/docs/varietystore/erp/yonyou/archives/unit","/docs/varietystore/erp/yonyou/archives/unit.md"]],
  ["v-2ac73b09","/docs/varietystore/erp/yonyou/archives/vendor-class.html",{"title":"供应商分类"},["/docs/varietystore/erp/yonyou/archives/vendor-class","/docs/varietystore/erp/yonyou/archives/vendor-class.md"]],
  ["v-cf42f4b6","/docs/varietystore/erp/yonyou/archives/vendor-inventory.html",{"title":"供应商存货对照表"},["/docs/varietystore/erp/yonyou/archives/vendor-inventory","/docs/varietystore/erp/yonyou/archives/vendor-inventory.md"]],
  ["v-e5459458","/docs/varietystore/erp/yonyou/archives/vendor.html",{"title":"供应商档案"},["/docs/varietystore/erp/yonyou/archives/vendor","/docs/varietystore/erp/yonyou/archives/vendor.md"]],
  ["v-0ab6aade","/docs/varietystore/erp/yonyou/archives/vouch-rd.html",{"title":"单据类型与收发类别对照表"},["/docs/varietystore/erp/yonyou/archives/vouch-rd","/docs/varietystore/erp/yonyou/archives/vouch-rd.md"]],
  ["v-1af00fd3","/docs/varietystore/erp/yonyou/archives/warehouse.html",{"title":"仓库档案"},["/docs/varietystore/erp/yonyou/archives/warehouse","/docs/varietystore/erp/yonyou/archives/warehouse.md"]],
  ["v-6d3f56a2","/docs/varietystore/erp/yonyou/buttons/",{"title":"按钮"},["/docs/varietystore/erp/yonyou/buttons/index.html","/docs/varietystore/erp/yonyou/buttons/README.md"]],
  ["v-51d7160a","/docs/varietystore/erp/yonyou/financial/accept.html",{"title":"收款单"},["/docs/varietystore/erp/yonyou/financial/accept","/docs/varietystore/erp/yonyou/financial/accept.md"]],
  ["v-41d69a70","/docs/varietystore/erp/yonyou/financial/capital-vouchers.html",{"title":"固定资产变动单"},["/docs/varietystore/erp/yonyou/financial/capital-vouchers","/docs/varietystore/erp/yonyou/financial/capital-vouchers.md"]],
  ["v-42d1a1d0","/docs/varietystore/erp/yonyou/financial/ought-pay.html",{"title":"应付单"},["/docs/varietystore/erp/yonyou/financial/ought-pay","/docs/varietystore/erp/yonyou/financial/ought-pay.md"]],
  ["v-52e24e3d","/docs/varietystore/erp/yonyou/financial/ought-receive.html",{"title":"应收单"},["/docs/varietystore/erp/yonyou/financial/ought-receive","/docs/varietystore/erp/yonyou/financial/ought-receive.md"]],
  ["v-bb789e5c","/docs/varietystore/erp/yonyou/financial/voucher.html",{"title":"凭证"},["/docs/varietystore/erp/yonyou/financial/voucher","/docs/varietystore/erp/yonyou/financial/voucher.md"]],
  ["v-382c788a","/docs/varietystore/erp/yonyou/package/",{"title":"打包"},["/docs/varietystore/erp/yonyou/package/index.html","/docs/varietystore/erp/yonyou/package/README.md"]],
  ["v-1d7e3d7c","/docs/varietystore/erp/yonyou/portal/",{"title":"门户开发"},["/docs/varietystore/erp/yonyou/portal/index.html","/docs/varietystore/erp/yonyou/portal/README.md"]],
  ["v-1c11eb9e","/docs/varietystore/erp/yonyou/reports/",{"title":"报表"},["/docs/varietystore/erp/yonyou/reports/index.html","/docs/varietystore/erp/yonyou/reports/README.md"]],
  ["v-fc3cec6c","/docs/varietystore/erp/yonyou/times/",{"title":"定时"},["/docs/varietystore/erp/yonyou/times/index.html","/docs/varietystore/erp/yonyou/times/README.md"]],
  ["v-bf8dfcee","/docs/varietystore/erp/yonyou/vouchers/",{"title":"业务单据"},["/docs/varietystore/erp/yonyou/vouchers/index.html","/docs/varietystore/erp/yonyou/vouchers/README.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]

export const pagesRoutes = routeItems.reduce(
  (result, [name, path, meta, redirects]) => {
    result.push(
      {
        name,
        path,
        component: Vuepress,
        meta,
      },
      ...redirects.map((item) => ({
        path: item,
        redirect: path,
      }))
    )
    return result
  },
  [
    {
      name: '404',
      path: '/:catchAll(.*)',
      component: Vuepress,
    }
  ]
)
