import type {SidebarConfig} from '@vuepress/theme-default'

export const zh:SidebarConfig={
    '/zh/guide/':[
        {
            text:'指南',
            children:[
                '/zh/guide/README.md',
            ]
        }
    ],
    '/zh/life/books':[
        {
            text:'书籍',
            children:[
                '/zh/life/books/README.md',
                '/zh/life/books/must-read-books.md',
            ]
        },{
            text:'概率论与数理统计(二)',
            children:[
                '/zh/life/books/self-study/probability-and-statistics/basic-formula.md',
                '/zh/life/books/self-study/probability-and-statistics/README.md',
                '/zh/life/books/self-study/probability-and-statistics/summary.md'
            ]
        }
    ],
    '/zh/life/music':[
        {
            text:'音乐',
            children:[
                '/zh/life/music/README.md',
            ]
        }
    ],
    '/zh/dotnet/':[
        {
            text:'Design Pattern',
            children:[
                '/zh/dotnet/design-pattern.md',
            ],
        },
        {
            text:'ABP.vNext',
            children:[
                '/zh/dotnet/abp.vnext/README.md',
                '/zh/dotnet/abp.vnext/data-dictionary.md',
            ],
        },
    ],
    '/zh/dotnet/wpf':[
        {
            text:'WPF',
            children:[
                '/zh/dotnet/wpf/README.md',
                '/zh/dotnet/wpf/download.md'
            ],
        },
        {
            text:'Prism',
            children:[
                '/zh/dotnet/wpf/prism/README.md',
            ],
        },
        {
            text:'Material Design In Xaml',
            children:[
                '/zh/dotnet/wpf/materialdesigninxaml/README.md',
            ],
        },
    ],
    '/zh/jquery/':[
        {
            text:'JQuery',
            children:[
                '/zh/jquery/README.md',
                '/zh/jquery/tips.md',
                '/zh/jquery/reference.md'
            ]
        }
    ],
    '/zh/database/sqlserver/':[
        {
            text:'SQL Server',
            children:[
                '/zh/database/sqlserver/README.md',
                '/zh/database/sqlserver/advance.md',
                '/zh/database/sqlserver/function.md',
                '/zh/database/sqlserver/sqlserver-sync-to-mysql.md',
                '/zh/database/sqlserver/sqlserver-sync-to-oracle.md',
                '/zh/database/sqlserver/tips.md',
                '/zh/database/sqlserver/reference.md',
            ]
        }
    ],
    '/zh/varietystore/erp/yonyou':[
        {
            text:'用友U8+',
            children:[
                '/zh/varietystore/erp/yonyou/README.md',
                '/zh/varietystore/erp/yonyou/archives/README.md',
                '/zh/varietystore/erp/yonyou/financial/README.md',
                '/zh/varietystore/erp/yonyou/portal/README.md',
                '/zh/varietystore/erp/yonyou/buttons/README.md',
                '/zh/varietystore/erp/yonyou/vouchers/README.md',
                '/zh/varietystore/erp/yonyou/reports/README.md',
                '/zh/varietystore/erp/yonyou/times/README.md',
                '/zh/varietystore/erp/yonyou/alarms/README.md',
                '/zh/varietystore/erp/yonyou/package/README.md',
            ]
        }
    ],
    '/zh/varietystore/office/excel':[
        {
            text:'Excel',
            children:[
                '/zh/varietystore/office/excel/README.md',
                '/zh/varietystore/office/excel/macro-sample1.md',
                '/zh/varietystore/office/excel/macro-sample2.md',
                '/zh/varietystore/office/excel/macro-sample3.md',
                '/zh/varietystore/office/excel/read-from-excel.md',
                '/zh/varietystore/office/excel/write-to-excel.md',
                '/zh/varietystore/office/excel/reference.md'
            ]
        }
    ],
    '/zh/varietystore/data-exchange-format/json':[
        {
            text:'JSON',
            children:[
                '/zh/varietystore/data-exchange-format/json/README.md',
                '/zh/varietystore/data-exchange-format/json/read-json.md',
                '/zh/varietystore/data-exchange-format/json/write-json.md',
                '/zh/varietystore/data-exchange-format/json/reference.md'
            ]
        }
    ],
    '/zh/varietystore/data-exchange-format/xml':[
        {
            text:'XML',
            children:[
                '/zh/varietystore/data-exchange-format/xml/README.md',
                '/zh/varietystore/data-exchange-format/xml/read-xml.md',
                '/zh/varietystore/data-exchange-format/xml/write-xml.md',
                '/zh/varietystore/data-exchange-format/xml/reference.md'
            ]
        }
    ],
    '/zh/varietystore/cli/github':[
        {
            text:'Github',
            children:[
                '/zh/varietystore/cli/github/README.md',
                '/zh/varietystore/cli/github/reference.md',
            ]
        }
    ],
    '/zh/varietystore/cli/yarn':[
        {
            text:'Yarn',
            children:[
                '/zh/varietystore/cli/yarn/README.md',
                '/zh/varietystore/cli/yarn/reference.md',
            ]
        }
    ],
    '/zh/varietystore/ladder':[
        {
            text:'梯云纵',
            children:[
                '/zh/varietystore/ladder/machinecode/README.md',
                '/zh/varietystore/ladder/sounds/README.md',
                '/zh/varietystore/ladder/google-recaptcha.md',
                '/zh/varietystore/ladder/encryption/README.md',
                '/zh/varietystore/ladder/transform/README.md',
            ]
        },
    ],
};